# ZMK Studioとマウス機能をオフ
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_MOUSE=n
CONFIG_PMW3610=n

# 【重要】バッテリー通知とエラーの回避
# 報告機能だけでなく、左右の通信用プロキシもオフにしてビルドエラーを防ぎます
CONFIG_ZMK_BATTERY_REPORTING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=n

# Bluetoothの接続を安定させる
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
