manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # ここを v0.3-branch から main に変更します
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: main
    - name: zmk-kscan-gpio-charlieplex
      remote: petejohanson
      revision: main

  self:
    path: config
